# rds variables
variable "project_name" {}
variable "environment" {}
variable "database_snapshot_identifier" {}
variable "database_instance_class" {}
variable "availability_zone_1" {}
variable "database_instance_identifier" {}
variable "multi_az_deployment" {}
variable "database_security_group_id" {}
variable "private_app_subnet_az1_id" {}
variable "private_app_subnet_az2_id" {}